import initScrollSuave from './modules/scroll-suave.js';
import initAnimacaoScroll from './modules/animacao-por-scroll.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tab-nav.js';
import { testando } from './modules/teste.js';
initTabNav();
initScrollSuave();
initAnimacaoScroll();
initAccordion();
testando();